name: spear

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconda::snakemake-minimal>=6.12, <7.0
  - bioconda::muscle=3.8
  - bioconda::bcftools>=1.14
  - conda-forge::pip>=21
  - python>=3.10
  - conda-forge::pandas>=1.3
  - conda-forge::biopython>=1.79
  - gawk
  - conda-forge::git>=2.30
  - conda-forge::openjdk>=11.0.9.1
  - conda-forge::sed
  - conda-forge::unzip
  - bioconda::grep
  - wget
  - conda-forge::pytables
  - pip
  - bioconda::gofasta==1.0.0
  - bioconda::minimap2==2.24
  - pip:
    - rich
    - plotly
    - tabulate==0.8.10
