name: spear

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconda::snakemake-minimal>=6.12
  - bioconda::muscle
  - bioconda::bcftools>=1.14
  - conda-forge::pip>=21
  - python>=3.10
  - conda-forge::pandas>=1.3
  - conda-forge::biopython>=1.79
  - bioconda::snakemake-minimal>=6.12
  - gawk
  - conda-forge::git>=2.30
  - conda-forge::openjdk>=11.0.9.1
  - conda-forge::sed
  - bioconda::grep
  - wget
